// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa412HqEqc52DHBQtns_ogk7RRZ4Chbps',
    appId: '1:299269538562:web:2b7a0c656282185524381b',
    messagingSenderId: '299269538562',
    projectId: 'app-dat-xe-38f38',
    authDomain: 'app-dat-xe-38f38.firebaseapp.com',
    databaseURL: 'https://app-dat-xe-38f38-default-rtdb.firebaseio.com',
    storageBucket: 'app-dat-xe-38f38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwKlb5YQpxLdX3haAb9Ed_QoJqYWEGA8',
    appId: '1:299269538562:android:0a7d8ce1cf70712024381b',
    messagingSenderId: '299269538562',
    projectId: 'app-dat-xe-38f38',
    databaseURL: 'https://app-dat-xe-38f38-default-rtdb.firebaseio.com',
    storageBucket: 'app-dat-xe-38f38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtXrr4EycZZVdzzK6XqsO-WKSTP5zUuAA',
    appId: '1:299269538562:ios:feb39f9302048bc224381b',
    messagingSenderId: '299269538562',
    projectId: 'app-dat-xe-38f38',
    databaseURL: 'https://app-dat-xe-38f38-default-rtdb.firebaseio.com',
    storageBucket: 'app-dat-xe-38f38.appspot.com',
    iosBundleId: 'com.example.usersApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtXrr4EycZZVdzzK6XqsO-WKSTP5zUuAA',
    appId: '1:299269538562:ios:9625685f2f559e5424381b',
    messagingSenderId: '299269538562',
    projectId: 'app-dat-xe-38f38',
    databaseURL: 'https://app-dat-xe-38f38-default-rtdb.firebaseio.com',
    storageBucket: 'app-dat-xe-38f38.appspot.com',
    iosBundleId: 'com.example.usersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoJ4lOLPcSjxLf3l1k5u4Q_QDJ6B1avyY',
    appId: '1:299269538562:web:4769741eeac189b324381b',
    messagingSenderId: '299269538562',
    projectId: 'app-dat-xe-38f38',
    authDomain: 'app-dat-xe-38f38.firebaseapp.com',
    databaseURL: 'https://app-dat-xe-38f38-default-rtdb.firebaseio.com',
    storageBucket: 'app-dat-xe-38f38.appspot.com',
  );
}
